name: CI
on:
  pull_request:
    branches: [master]
  push:
    branches: [master, release]
jobs:
  build-my-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Building my application!"

  deploy-serialize: # we could also try the new concurrency feature here...
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    needs: [build-my-app]
    steps:
      - name: wait for other deployments to complete first
        uses: meisterplan/action-turnstyle@v2
        with:
          abort-after-seconds: 600
          poll-interval-seconds: 10
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-staging:
    if: github.ref == 'refs/heads/master'
    environment: staging
    needs: [deploy-serialize]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying to Staging System!"

  deploy-prod-eu:
    if: github.ref == 'refs/heads/release'
    environment: production
    needs: [deploy-serialize]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying to PROD EU!"

  deploy-prod-us:
    if: github.ref == 'refs/heads/release'
    environment: production
    needs: [ deploy-prod-eu ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying to PROD US!"