name: CI
on:
  pull_request:
    branches: [master]
  push:
    branches: [master, release]
jobs:
  build-my-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Building my application!"

  deploy-staging:
    if: github.ref == 'refs/heads/master'
    environment: staging
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    needs: [deploy-serialize]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying to Staging System!"

  deploy-prod-eu:
    if: github.ref == 'refs/heads/release'
    environment: production
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    needs: [deploy-serialize]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying to PROD EU!"

  deploy-prod-us:
    if: github.ref == 'refs/heads/release'
    environment: production
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    needs: [ deploy-prod-eu ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying to PROD US!"